[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#4682b4"
backgroundColor = "#121212"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"

[global]
developmentMode = false
showWarningOnDirectExecution = true

[server]
enableCORS = true
enableXsrfProtection = true
fileWatcherType = "auto"

[browser.serverAddress]
value = "localhost"

[browser.serverPort]
value = 8501
